project:
  type: website
  output-dir: docs

website:
  site-url: https://anthonyrocher.github.io/Master-s-Thesis-Website
  title: "Master's Thesis"
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "Paper"
        href: paper.html
      - text: "Data"
        href: data.html
      - text: "Workflow"
        href: workflow.html
      - text: "Design"
        href: design.html
  search: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true