---
title: "Theory and Empirical Design"
editor: visual
bibliography: references.bib
---

### A theoritical framework

Let $p$ denote the subjective probability that a property will be hit by an earthquake. $p$ depends on both the information set $i$ that individuals possess about seismic risks (such as recent events, media coverage, etc.), and $r$, the objective attributes that make earthquakes more likely to occur, such as being located on seismic faults. Note that $\pi$, the objective probability of an earthquake, is included in $i$ in our case, since maps are provided and publicly available.

The Hedonic Price Function is given by: $$
P = P(Z, r, p(i, r))
$$

where $P$ denotes the price of the house and $Z$ denotes an additional set of structural, environmental, and locational characteristics not related to the seismic hazard maps.

Following @brookshire_test_1985, the decision of agents is modeled using a state-dependent expected utility function: $$
EU = p(i, r) \cdot U^E[Z, r, Q] + (1 - p(i, r)) \cdot U^{NE}[Z, r, Q],
$$ where $U^E(\cdot)$ is the homeowner's utility in the event of an earthquake, and $U^{NE}(\cdot)$ is the homeowner's utility when no such event occurs. Here, $Q$ is a composite commodity, and the budget constraint of the homeowner is: $$
M = P(Z, r, p(i, r)) + Q.
$$

Maximizing expected utility with respect to $p$, subject to the budget constraint, and then dividing by the expected marginal utility of income yields: $$
\frac{\partial P}{\partial p} = \frac{U^{E} - U^{NE}}{p(i,r)\frac{\partial U^{E}}{\partial Q} + \left(1 - p(i,r)\right)\frac{\partial U^{NE}}{\partial Q}}.
$$

### The empirical strategy

Most of the papers set risk as a property attribute, and the use hedonic price approach as introduced by @rosen1974. This approach uses DiD terminology:

$$
\ln P_{it} = \alpha_0 + \sum_{j=1}^{J} \alpha_j Z_{ij} + \beta r_i + \gamma Exposed_i + \delta Post_{it} + \theta_t (Post_{it} \times Exposed_i) + \varepsilon_{it}
$$

\- $\ln P_{it}$: log property price for unit $i$ at time $t$

\- $Z_{ij}$: vector of property and location controls

\- $r_i$: location fixed effects (prefectures)

\- $Exposed_i$: baseline seismic risk exposure (over $p = 0.3$)

\- $Post_{it}$: earthquake occurrence/intensity at time $t$

\- $Post_{it} \times Exposed_i$: interaction capturing heterogeneous effects

In practice, this is my first attempt:

``` stata
regress log_price ///
    sqft age ///
    parking_y ///
    walk_distance1 super_distance hospital_distance park_distance ///
    pop_total_linear ///
    employement_linear_rate ///
    net_migration ///
    foreigners_linear_share ///
    c.earthquake##c.seismic ///
    i.prefecture, robust
```

## Empirical strategy (2)

$$
\ln P_{it} = \alpha_0 + \sum_{j=1}^{J} \alpha_j Z_{ij} + \beta r_i + \gamma Exposed_i + \delta Post_{it} + \theta_t (Post_{it} \times Exposed_i \times Distance_i) + \varepsilon_{it}
$$

## References
